%FUNCTIE PENTRU AFISARE SCHEMA CIRCUIT
function Buton_introducere

figure('Name','Schema circuit',...     
    'Units','normalized',...           
    'Position',[0.2 0.2 0.3 0.2],...   
    'Color',[0.2 0.2 0.2],...;
    'NumberTitle','off'); 
    

w2 = imread('schema.png');
imshow(w2,'InitialMagnification',100);

%PUSHBUTTON CLOSE SCHEMA CIRCUIT
uicontrol('Style','pushbutton',...   
    'Units','normalized',...  
    'Position',[0.58 0.265 0.12 0.07],...
    'String','Close',...
    'Callback','close'); 
end