Fig=figure('Name','Proiect Nașca Marian Florin',...
'Units','normalized',...
'Position',[0.1 0.1 0.8 0.8],...
'NumberTitle','off');
l=axes('units','normalized',...
    'position',[0 0 1 1]);
uistack(l,'bottom');
I=imread('wallpaper.jpg');
q=imagesc(I);
set(gca,'Position',[0 0 1 1]);
set(q,'alphadata',.95);
colormap gray
set(l,'handlevisibility','off',...
    'visible','off');


      %---------------Grup de meniuri----------%
m=uimenu('Label','Documentatie Proiect');
   uimenu(m,'Label','Autor','Callback','open(''Autor.pdf'')');
   uimenu(m,'Label','Teorie','Callback','open(''Teorie.pdf'')');
   uimenu(m,'Label','Close','Callback','close','Separator','on','Accelerator','Q');

%TITLU   
uicontrol('Style','text',...  
    'Units','normalized',...     
    'Position',[0.2 0.8 0.55 0.08],...   
    'backgroundcolor','b',...             
    'foregroundcolor','w',...,
    'fontname','Times New Roman',...
    'fontsize',30,...
    'String','AMPLIFICATOR   DIFERENTIAL');

%PUSHBUTTON DESCHIDERE PROGRAM
uicontrol('Style','Pushbutton',...  
    'Units','normalized',...     
     'Position',[0.4 0.6 0.2 0.1],... 
    'backgroundcolor','k',...             
    'foregroundcolor','w',...,
    'fontname','Times New Roman',...
    'fontsize',25,...
    'fontangle','italic',...
    'String','Program',...
    'Callback','proiect');


%PUSHBUTTON DESCHIDERE PREZENTARE POWERPOINT
 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.4 0.4 0.2 0.1],... 
          'string','Prezentare PPT',...
          'backgroundcolor','k',...             
    'foregroundcolor','w',...,
    'fontname','Times New Roman',...
    'fontangle','italic',...
    'fontsize',25,...
    'String','Prezentare PPT',...
          'Callback','open (''Prezentare.pptx'')');

%PUSHBUTTON DESCHIDERE BIBLIOGRAFIE 
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.4 0.2 0.2 0.1],... 
          'string','Bibliografie',...
          'backgroundcolor','k',...             
    'foregroundcolor','w',...,
    'fontname','Times New Roman',...
    'fontangle','italic',...
    'fontsize',25,...
    'String','Bibliografie',...
          'Callback','open (''Bibliografie.pdf'')');


%PUSHBUTTON INCHIDERE PAGINA DE START
uicontrol('style','pushbutton',...
              'Units','normalized',...
              'String',' INCHIDE',...
              'backgroundcolor','k',...             
    'foregroundcolor','w',...,
    'fontname','Times New Roman',...
    'fontangle','italic',...
    'fontsize',25,...
    'String','Inchide',...
              'Position',[0.4 0 0.2 0.1],...
              'Callback','close;');
